apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: yst0uqjkr-go 
  janus-idp.io/tekton: yst0uqjkr-go
  backstage.io/kubernetes-id: yst0uqjkr-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yst0uqjkr-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml